name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install doc8 restructuredtext-lint
      
      - name: Check RST syntax
        run: |
          find . -type f -name "*.rst" -exec rst-lint {} \;
      
      - name: Run doc8
        run: |
          doc8 docs/

      - name: Check for broken links
        run: |
          pip install sphinx-link-checker
          cd docs
          make linkcheck
